"""Structural protocols for the API clients ViewModels depend on.

ViewModels type-hint against these, not the concrete ``httpx``-backed
classes, so tests can supply plain fake objects (matching the protocol
structurally -- no inheritance needed) with zero network involved.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from frontend.mechanic_shop.models.attachment import Attachment
from frontend.mechanic_shop.models.customer import Customer
from frontend.mechanic_shop.models.estimate import Estimate
from frontend.mechanic_shop.models.invoice import Invoice, InvoiceTotals, Payment
from frontend.mechanic_shop.models.line_item import LineItem
from frontend.mechanic_shop.models.repair_order import InspectionChecklistItem, RepairOrder
from frontend.mechanic_shop.models.signature import Signature
from frontend.mechanic_shop.models.vehicle import TimelineEvent, Vehicle, VinDecodeResult


class CustomerApiClientProtocol(Protocol):
    def list_customers(
        self, query: str | None = None, limit: int = 50, offset: int = 0
    ) -> tuple[list[Customer], int]: ...
    def get_customer(self, customer_id: int) -> Customer: ...
    def create_customer(self, customer: Customer) -> Customer: ...
    def update_customer(self, customer_id: int, customer: Customer) -> Customer: ...
    def deactivate_customer(self, customer_id: int) -> Customer: ...
    def list_customer_vehicles(self, customer_id: int) -> list[Vehicle]: ...


class VehicleApiClientProtocol(Protocol):
    def list_vehicles(
        self, query: str | None = None, limit: int = 50, offset: int = 0
    ) -> tuple[list[Vehicle], int]: ...
    def get_vehicle(self, vehicle_id: int) -> Vehicle: ...
    def create_vehicle(
        self, vehicle: Vehicle, initial_mileage: int | None = None, skip_vin_decode: bool = False
    ) -> Vehicle: ...
    def update_vehicle(self, vehicle_id: int, vehicle: Vehicle) -> Vehicle: ...
    def deactivate_vehicle(self, vehicle_id: int) -> Vehicle: ...
    def decode_vin(self, vin: str, allow_online_lookup: bool = True) -> VinDecodeResult: ...
    def add_mileage(
        self, vehicle_id: int, mileage: int, source: str, notes: str | None = None
    ) -> Vehicle: ...
    def get_timeline(self, vehicle_id: int) -> list[TimelineEvent]: ...


class EstimateApiClientProtocol(Protocol):
    def list_estimates(self, limit: int = 50, offset: int = 0) -> tuple[list[Estimate], int]: ...
    def list_for_vehicle(self, vehicle_id: int) -> list[Estimate]: ...
    def get_estimate(self, estimate_id: int) -> Estimate: ...
    def create_estimate(self, estimate: Estimate) -> Estimate: ...
    def update_estimate(self, estimate_id: int, estimate: Estimate) -> Estimate: ...
    def delete_estimate(self, estimate_id: int) -> None: ...
    def list_line_items(self, estimate_id: int) -> list[LineItem]: ...
    def replace_line_items(self, estimate_id: int, items: list[LineItem]) -> list[LineItem]: ...
    def send_estimate(self, estimate_id: int) -> Estimate: ...
    def approve_estimate(self, estimate_id: int, signer_name: str | None = None) -> Estimate: ...
    def decline_estimate(self, estimate_id: int) -> Estimate: ...
    def convert_to_repair_order(self, estimate_id: int) -> RepairOrder: ...


class RepairOrderApiClientProtocol(Protocol):
    def list_repair_orders(
        self,
        status: str | None = None,
        query: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[RepairOrder], int]: ...
    def list_for_vehicle(self, vehicle_id: int) -> list[RepairOrder]: ...
    def get_repair_order(self, repair_order_id: int) -> RepairOrder: ...
    def create_repair_order(self, repair_order: RepairOrder) -> RepairOrder: ...
    def update_repair_order(
        self, repair_order_id: int, repair_order: RepairOrder
    ) -> RepairOrder: ...
    def update_status(self, repair_order_id: int, status: str) -> RepairOrder: ...
    def cancel_repair_order(self, repair_order_id: int) -> RepairOrder: ...
    def list_line_items(self, repair_order_id: int) -> list[LineItem]: ...
    def replace_line_items(self, repair_order_id: int, items: list[LineItem]) -> list[LineItem]: ...
    def replace_checklist_items(
        self, repair_order_id: int, items: list[InspectionChecklistItem]
    ) -> list[InspectionChecklistItem]: ...
    def add_signature(self, repair_order_id: int, signature: Signature) -> Signature: ...
    def list_signatures(self, repair_order_id: int) -> list[Signature]: ...
    def convert_to_invoice(
        self,
        repair_order_id: int,
        tax_rate: float = 0,
        warranty_notes: str | None = None,
        due_date: str | None = None,
    ) -> Invoice: ...


class InvoiceApiClientProtocol(Protocol):
    def list_invoices(
        self,
        status: str | None = None,
        query: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[Invoice], int]: ...
    def list_for_vehicle(self, vehicle_id: int) -> list[Invoice]: ...
    def get_invoice(self, invoice_id: int) -> Invoice: ...
    def update_invoice(self, invoice_id: int, invoice: Invoice) -> Invoice: ...
    def send_invoice(self, invoice_id: int) -> Invoice: ...
    def void_invoice(self, invoice_id: int) -> Invoice: ...
    def list_line_items(self, invoice_id: int) -> list[LineItem]: ...
    def replace_line_items(self, invoice_id: int, items: list[LineItem]) -> list[LineItem]: ...
    def get_totals(self, invoice_id: int) -> InvoiceTotals: ...
    def list_payments(self, invoice_id: int) -> list[Payment]: ...
    def record_payment(self, invoice_id: int, payment: Payment) -> Payment: ...
    def void_payment(self, invoice_id: int, payment_id: int) -> Invoice: ...
    def get_pdf(self, invoice_id: int) -> bytes: ...


class AttachmentApiClientProtocol(Protocol):
    def upload(
        self,
        entity_type: str,
        entity_id: int,
        file_path: Path,
        attachment_type: str,
        description: str | None = None,
        photo_stage: str | None = None,
    ) -> Attachment: ...
    def list_for_entity(self, entity_type: str, entity_id: int) -> list[Attachment]: ...
    def get_attachment(self, attachment_id: int) -> Attachment: ...
    def download(self, attachment_id: int) -> bytes: ...
    def delete_attachment(self, attachment_id: int) -> None: ...
