"""Structural protocols for the API clients ViewModels depend on.

ViewModels type-hint against these, not the concrete ``httpx``-backed
classes, so tests can supply plain fake objects (matching the protocol
structurally -- no inheritance needed) with zero network involved.
"""

from __future__ import annotations

from typing import Protocol

from frontend.mechanic_shop.models.customer import Customer
from frontend.mechanic_shop.models.vehicle import TimelineEvent, Vehicle, VinDecodeResult


class CustomerApiClientProtocol(Protocol):
    def list_customers(
        self, query: str | None = None, limit: int = 50, offset: int = 0
    ) -> tuple[list[Customer], int]: ...
    def get_customer(self, customer_id: int) -> Customer: ...
    def create_customer(self, customer: Customer) -> Customer: ...
    def update_customer(self, customer_id: int, customer: Customer) -> Customer: ...
    def deactivate_customer(self, customer_id: int) -> Customer: ...
    def list_customer_vehicles(self, customer_id: int) -> list[Vehicle]: ...


class VehicleApiClientProtocol(Protocol):
    def list_vehicles(
        self, query: str | None = None, limit: int = 50, offset: int = 0
    ) -> tuple[list[Vehicle], int]: ...
    def get_vehicle(self, vehicle_id: int) -> Vehicle: ...
    def create_vehicle(
        self, vehicle: Vehicle, initial_mileage: int | None = None, skip_vin_decode: bool = False
    ) -> Vehicle: ...
    def update_vehicle(self, vehicle_id: int, vehicle: Vehicle) -> Vehicle: ...
    def deactivate_vehicle(self, vehicle_id: int) -> Vehicle: ...
    def decode_vin(self, vin: str, allow_online_lookup: bool = True) -> VinDecodeResult: ...
    def add_mileage(
        self, vehicle_id: int, mileage: int, source: str, notes: str | None = None
    ) -> Vehicle: ...
    def get_timeline(self, vehicle_id: int) -> list[TimelineEvent]: ...
