"""phase3 parts suppliers diagnostics reports

Revision ID: 1b63f3de6392
Revises: 1f0737ee3244
Create Date: 2026-08-03 13:33:48.634640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b63f3de6392'
down_revision: Union[str, None] = '1f0737ee3244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_NUMBER_SEQUENCE_TABLE = sa.table(
    "number_sequences",
    sa.column("entity_type", sa.String),
    sa.column("prefix", sa.String),
    sa.column("next_value", sa.Integer),
)

_NUMBER_SEQUENCE_SEED_ROWS = [
    {"entity_type": "purchase_order", "prefix": "PO", "next_value": 1},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_suppliers_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_suppliers_name', ['name'], unique=False)

    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('oem_number', sa.String(length=100), nullable=True),
    sa.Column('aftermarket_number', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('core_charge', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('minimum_stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shelf_location', sa.String(length=50), nullable=True),
    sa.Column('warranty_text', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_parts_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parts'))
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index('idx_parts_barcode', ['barcode'], unique=True, sqlite_where=sa.text('barcode IS NOT NULL'))
        batch_op.create_index('idx_parts_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_parts_part_number', ['part_number'], unique=True)
        batch_op.create_index('idx_parts_supplier_id', ['supplier_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('idx_purchase_orders_status', ['status'], unique=False)
        batch_op.create_index('idx_purchase_orders_supplier_id', ['supplier_id'], unique=False)
        batch_op.create_index('uq_purchase_orders_purchase_order_number', ['purchase_order_number'], unique=True)

    op.create_table('part_compatibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_part_compatibility_part_id_parts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_compatibility'))
    )
    with op.batch_alter_table('part_compatibility', schema=None) as batch_op:
        batch_op.create_index('idx_part_compatibility_make_model', ['make', 'model'], unique=False)
        batch_op.create_index('idx_part_compatibility_part_id', ['part_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_purchase_order_items_part_id_parts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items'))
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index('idx_purchase_order_items_part_id', ['part_id'], unique=False)
        batch_op.create_index('idx_purchase_order_items_purchase_order_id', ['purchase_order_id'], unique=False)

    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mileage_at_time', sa.Integer(), nullable=True),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], name=op.f('fk_diagnostic_sessions_repair_order_id_repair_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_diagnostic_sessions_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_sessions'))
    )
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_diagnostic_sessions_vehicle_id', ['vehicle_id'], unique=False)

    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_inventory_adjustments_part_id_parts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_inventory_adjustments_purchase_order_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], name=op.f('fk_inventory_adjustments_repair_order_id_repair_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_adjustments_part_id_created_at', ['part_id', 'created_at'], unique=False)
        batch_op.create_index('idx_inventory_adjustments_reason', ['reason'], unique=False)

    op.create_table('diagnostic_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('reading_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_within_spec', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], name=op.f('fk_diagnostic_readings_session_id_diagnostic_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_readings'))
    )
    with op.batch_alter_table('diagnostic_readings', schema=None) as batch_op:
        batch_op.create_index('idx_diagnostic_readings_session_id', ['session_id'], unique=False)

    op.create_table('diagnostic_trouble_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('freeze_frame_data', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], name=op.f('fk_diagnostic_trouble_codes_session_id_diagnostic_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_trouble_codes'))
    )
    with op.batch_alter_table('diagnostic_trouble_codes', schema=None) as batch_op:
        batch_op.create_index('idx_diagnostic_trouble_codes_session_id', ['session_id'], unique=False)

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_line_items_part_id', ['part_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_line_items_part_id_parts'), 'parts', ['part_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_technician', sa.String(length=150), nullable=True))

    op.bulk_insert(_NUMBER_SEQUENCE_TABLE, _NUMBER_SEQUENCE_SEED_ROWS)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(_NUMBER_SEQUENCE_TABLE.delete().where(
        _NUMBER_SEQUENCE_TABLE.c.entity_type == "purchase_order"
    ))

    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('assigned_technician')

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_line_items_part_id_parts'), type_='foreignkey')
        batch_op.drop_index('idx_line_items_part_id')
        batch_op.drop_column('part_id')

    with op.batch_alter_table('diagnostic_trouble_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnostic_trouble_codes_session_id')

    op.drop_table('diagnostic_trouble_codes')
    with op.batch_alter_table('diagnostic_readings', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnostic_readings_session_id')

    op.drop_table('diagnostic_readings')
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_adjustments_reason')
        batch_op.drop_index('idx_inventory_adjustments_part_id_created_at')

    op.drop_table('inventory_adjustments')
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnostic_sessions_vehicle_id')

    op.drop_table('diagnostic_sessions')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_purchase_order_items_purchase_order_id')
        batch_op.drop_index('idx_purchase_order_items_part_id')

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('part_compatibility', schema=None) as batch_op:
        batch_op.drop_index('idx_part_compatibility_part_id')
        batch_op.drop_index('idx_part_compatibility_make_model')

    op.drop_table('part_compatibility')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('uq_purchase_orders_purchase_order_number')
        batch_op.drop_index('idx_purchase_orders_supplier_id')
        batch_op.drop_index('idx_purchase_orders_status')

    op.drop_table('purchase_orders')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index('idx_parts_supplier_id')
        batch_op.drop_index('idx_parts_part_number')
        batch_op.drop_index('idx_parts_is_active')
        batch_op.drop_index('idx_parts_barcode', sqlite_where=sa.text('barcode IS NOT NULL'))

    op.drop_table('parts')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('idx_suppliers_name')
        batch_op.drop_index('idx_suppliers_is_active')

    op.drop_table('suppliers')
    # ### end Alembic commands ###
