"""initial schema

Revision ID: fdb988e0e552
Revises: 
Create Date: 2026-08-01 19:43:49.300394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fdb988e0e552'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachments_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), server_default='phone', nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customers_business_name', ['business_name'], unique=False)
        batch_op.create_index('idx_customers_email', ['email'], unique=False)
        batch_op.create_index('idx_customers_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_customers_last_name_first_name', ['last_name', 'first_name'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('idx_notes_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('vin_decode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('decoded_json', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('drive_type', sa.String(length=10), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('decoded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vin_decode_cache'))
    )
    with op.batch_alter_table('vin_decode_cache', schema=None) as batch_op:
        batch_op.create_index('uq_vin_decode_cache_vin', ['vin'], unique=True)

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_phone_numbers_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers'))
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index('idx_phone_numbers_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_phone_numbers_phone_number', ['phone_number'], unique=False)
        batch_op.create_index('uq_phone_numbers_one_primary_per_customer', ['customer_id'], unique=True, sqlite_where=sa.text('is_primary = 1'))

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_attachment_id', sa.Integer(), nullable=True),
    sa.Column('related_note_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_attachment_id'], ['attachments.id'], name=op.f('fk_timeline_events_related_attachment_id_attachments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_note_id'], ['notes.id'], name=op.f('fk_timeline_events_related_note_id_notes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index('idx_timeline_events_entity', ['entity_type', 'entity_id', sa.literal_column('event_timestamp DESC')], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('drive_type', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('license_plate_state', sa.String(length=2), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('current_mileage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('vin_decode_source', sa.String(length=10), server_default='none', nullable=False),
    sa.Column('vin_decoded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_vehicles_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicles_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_vehicles_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_vehicles_license_plate_state', ['license_plate', 'license_plate_state'], unique=False)
        batch_op.create_index('uq_vehicles_vin', ['vin'], unique=True)

    op.create_table('mileage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mileage >= 0', name=op.f('ck_mileage_records_mileage_non_negative')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_mileage_records_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mileage_records'))
    )
    with op.batch_alter_table('mileage_records', schema=None) as batch_op:
        batch_op.create_index('idx_mileage_records_vehicle_id_recorded_at', ['vehicle_id', 'recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mileage_records', schema=None) as batch_op:
        batch_op.drop_index('idx_mileage_records_vehicle_id_recorded_at')

    op.drop_table('mileage_records')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('uq_vehicles_vin')
        batch_op.drop_index('idx_vehicles_license_plate_state')
        batch_op.drop_index('idx_vehicles_is_active')
        batch_op.drop_index('idx_vehicles_customer_id')

    op.drop_table('vehicles')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('idx_timeline_events_entity')

    op.drop_table('timeline_events')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index('uq_phone_numbers_one_primary_per_customer', sqlite_where=sa.text('is_primary = 1'))
        batch_op.drop_index('idx_phone_numbers_phone_number')
        batch_op.drop_index('idx_phone_numbers_customer_id')

    op.drop_table('phone_numbers')
    with op.batch_alter_table('vin_decode_cache', schema=None) as batch_op:
        batch_op.drop_index('uq_vin_decode_cache_vin')

    op.drop_table('vin_decode_cache')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('idx_notes_entity')

    op.drop_table('notes')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customers_last_name_first_name')
        batch_op.drop_index('idx_customers_is_active')
        batch_op.drop_index('idx_customers_email')
        batch_op.drop_index('idx_customers_business_name')

    op.drop_table('customers')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachments_entity')

    op.drop_table('attachments')
    # ### end Alembic commands ###
